---
all:
    vars:
      ansible_user: azureuser
      ansible_ssh_private_key_file: ./sshkey
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    children:
      jenkins:
        hosts:
          "techstarter.ddns.net":
            ansible_host: 13.80.133.147
      webserver:
        hosts:
          "techstarter3.ddns.net":
            ansible_host: 20.224.219.216